'use client';
import { useEffect, useState } from 'react';
import { Activity, ArrowDownUp, ArrowRight, ArrowUpRight, Check, ChevronRight, CircleHelp, Crosshair, Crown, ExternalLink, Eye, Gauge, LockKeyhole, LogOut, Radio, ShieldCheck, Target, Trophy, Users, Wallet, Zap } from 'lucide-react';
import { getWallets } from '@wallet-standard/app';
import bs58 from 'bs58';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Progress } from '@/components/ui/progress';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table';
import { Switch } from '@/components/ui/switch';
import { Arena } from './arena';
import { RoundOutcome } from './round-outcome';
import { OwnerReview } from './owner-review';
import { FundingWidget, EligibilityWidget, LobbyWidget, RoundStats, NetworkStats, LeaderPreview, LoopWidget } from './widgets';
import { api, useGame } from './use-game';
import { shortWallet } from '@/shared/game';
import type { Settings } from '@/shared/types';

const money=(n=0)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
const timer=(ms:number)=>{const sec=Math.max(0,Math.ceil(ms/1000));return `${Math.floor(sec/60).toString().padStart(2,'0')}:${(sec%60).toString().padStart(2,'0')}`;};
export function Grailshot({page}:{page:'arena'|'leaderboard'|'profile'|'admin'}) {
  const game=useGame(),{snapshot,player,holding}=game, [walletOpen,setWalletOpen]=useState(false),[rules,setRules]=useState(false),[wallets,setWallets]=useState<any[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[fps,setFps]=useState(0),[practice,setPractice]=useState(false),[now,setNow]=useState(Date.now());
  const [leaders,setLeaders]=useState<any[]>([]),[profile,setProfile]=useState<any>(null),[name,setName]=useState(''),[settings,setSettings]=useState<Settings|null>(null),[jobs,setJobs]=useState<any[]>([]),[purchaseError,setPurchaseError]=useState('');
  useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),250);return()=>clearInterval(id);},[]);
  useEffect(()=>{const registry=getWallets();const update=()=>setWallets(registry.get().filter(w=>'standard:connect' in w.features&&'solana:signMessage' in w.features));update();const off=registry.on('register',update);return()=>off();},[]);
  useEffect(()=>{setLeaders([]);setProfile(null);},[snapshot?.mint]);
  useEffect(()=>{let disposed=false;api('/leaderboard').then(x=>{if(!disposed)setLeaders(x.players);}).catch(()=>{});return()=>{disposed=true;};},[snapshot?.round?.status,snapshot?.mint]);
  useEffect(()=>{
    let disposed=false;
    if(page==='profile'&&player)api(`/profiles/${player.wallet}`).then(x=>{if(!disposed){setProfile(x);setName(x.name);}}).catch(e=>{if(!disposed)setNotice(e.message);});
    if(page==='admin'&&player?.owner)api('/admin').then(x=>{if(disposed)return;setSettings(x.settings);setJobs(x.jobs);setPurchaseError(['purchasing','review'].includes(x.round?.status)?x.audit?.find((a:any)=>a.event==='pack-delay'&&a.data.round===x.round.id)?.data.error??'':'');}).catch(e=>{if(!disposed)setNotice(e.message);});
    return()=>{disposed=true;};
  },[page,player,snapshot?.round?.status,snapshot?.mint]);
  async function connect(wallet:any) {setBusy(true);setNotice('');try { const result=await wallet.features['standard:connect'].connect();const account=result.accounts.find((a:any)=>a.chains.some((c:string)=>c.startsWith('solana:')));if(!account)throw new Error('Choose a Solana account.');const challenge=await api('/auth/challenge',{wallet:account.address});const [signed]=await wallet.features['solana:signMessage'].signMessage({account,message:new TextEncoder().encode(challenge.message)});await api('/auth/verify',{id:challenge.id,signature:bs58.encode(signed.signature)});await game.refreshPlayer();setWalletOpen(false);}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
  async function join() {if(!player){setWalletOpen(true);return;}setBusy(true);try{await api('/rounds/join',{});setNotice('You’re in. Stay online for the countdown.');setPractice(false);}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
  async function logout(){await api('/auth/logout',{});await game.refreshPlayer();setProfile(null);}
  const treasury=snapshot?.treasury,round=snapshot?.round,joined=round?.registered,displayRound=round??game.latestResult;
  const joinLabel=busy?'Please wait…':!player?'Connect wallet to enter':joined?'You’re in the round':!holding?.configured?'Awaiting token launch':!holding.eligible?'Check your eligibility':round?.status==='registration'?'Enter live round':'Join the next round';
  const timedRound=round&&['registration','countdown','live','complete','carried'].includes(round.status)&&round.deadline>now+game.offset.current;
  const countdown=timedRound?timer(round.deadline-now-game.offset.current):round?.status==='purchasing'?'Opening':round?.status==='awarding'?'Sending':round?.status==='adjudicating'?'Checking':round?.status==='review'||treasury?.paused?'On hold':!treasury?.enabled?'At launch':!treasury.ready?'Checking':treasury.nextPackTier?'Opening':'Funding';
  return <div className="site-shell">
    <header className="site-header"><a className="brand" href="/" aria-label="Grailshot home"><img className="brand-wordmark" src="/brand/grailshot-wordmark-v5.webp" alt="GRAILSHOT" width={690} height={161} fetchPriority="high"/></a><nav aria-label="Main navigation"><a className={page==='arena'?'selected':''} href="/"><span className="nav-number">01</span><Crosshair size={16}/><span>Arena</span></a><a className={page==='leaderboard'?'selected':''} href="/leaderboard"><span className="nav-number">02</span><Trophy size={16}/><span>Rankings</span></a><a className={page==='profile'?'selected':''} href="/profile"><span className="nav-number">03</span><Users size={16}/><span>Profile</span></a>{player?.owner&&<a className={page==='admin'?'selected':''} href="/admin">Control room</a>}</nav><div className="header-actions">{snapshot?.mint&&<div className="contract-chip"><button title={snapshot.mint} aria-label={`Copy coin contract address ${snapshot.mint}`} onClick={async()=>{try{await navigator.clipboard.writeText(snapshot.mint!);setNotice('Contract address copied.');}catch{setNotice(`Contract address: ${snapshot.mint}`);}}}><span>CA</span><code>{shortWallet(snapshot.mint)}</code><span>Copy</span></button><a href={`https://solscan.io/token/${snapshot.mint}`} target="_blank" rel="noreferrer" aria-label="Verify coin contract on Solscan"><ExternalLink size={14}/></a></div>}<a className="social-link" href="https://x.com/grailshotxyz" target="_blank" rel="noopener noreferrer" aria-label="Follow GRAILSHOT on X (opens in a new tab)" title="@grailshotxyz"><svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true" fill="currentColor"><path d="M18.9 2H22l-6.8 7.8L23.2 22h-6.3L12 14.6 5.5 22H2.4l8.1-9.4L.8 2h6.5l4.5 6.8L18.9 2ZM17.8 20h1.7L6.3 3.9H4.5L17.8 20Z"/></svg></a><Button className="wallet-button" onClick={()=>player?void logout():setWalletOpen(true)}>{player?<LogOut size={15}/>:<Wallet size={15}/>}<span>{player?shortWallet(player.wallet):'Connect wallet'}</span></Button></div></header>
    <main className="main-content">
      <div className="page-heading"><div><div className="eyebrow"><span className="orange-dash"/>THE HOLDER’S ARENA</div><h1>{page==='arena'?'AIM HIGH. WIN GRAILS.':page==='leaderboard'?'THE SHARPEST SHOTS.':page==='profile'?'YOUR SHOT AT GLORY.':'THE CONTROL ROOM.'}</h1><p>{page==='arena'?'Real cards. Real opponents. One shot at the top.':page==='leaderboard'?'Every win earned. Every card delivered on-chain.':page==='profile'?'Your wallet. Your wins. Your collection.':'Treasury, automation, and round recovery.'}</p></div><div className="heading-actions"><span className="online-pill"><i className={game.connection==='connected'?'live-dot':'waiting-dot'}/>{snapshot?.online??0} online</span><button className="rules-button" onClick={()=>setRules(true)}><CircleHelp size={16}/>How to play</button></div></div>
      {(notice||game.error)&&<div className="notice" role="status"><span>{notice||game.error}</span><button onClick={()=>{setNotice('');game.setError('');}} aria-label="Dismiss notification">×</button></div>}
      {page==='arena'&&<>
        <div className="game-grid"><section className="arena-column"><div className="section-bar"><div><Radio size={15}/><span>LIVE ARENA</span><span className="round-id">{displayRound?`ROUND #${String(displayRound.number).padStart(4,'0')}`:'PRE-LAUNCH'}</span></div><span className="status-tag">{practice?'PRACTICE':displayRound?.status.replaceAll('_',' ').toUpperCase()||'LOBBY OPEN'}</span></div>
          <Arena round={displayRound??null} wallet={player?.wallet} shotResult={game.shotResult} offset={game.offset} onShot={game.shoot} onFps={setFps} onJoin={join} joinLabel={joinLabel} practice={practice} setPractice={setPractice}/>
          <RoundStats round={round} countdown={countdown}/>
          <NetworkStats connection={game.connection} ping={game.ping} jitter={game.jitter} timeouts={game.timeouts} fps={fps} rpc={treasury?.rpc}/>
          {round?.message&&<p className="round-message">{round.message}</p>}{game.latestResult&&round&&round.id!==game.latestResult.id&&<section className="recent-result"><RoundOutcome round={game.latestResult} wallet={player?.wallet} compact/></section>}
        </section>
        <aside className="right-rail">
          <FundingWidget treasury={treasury}/>
          <EligibilityWidget holding={holding} connected={!!player} onCheck={()=>player?void game.refreshPlayer().then(()=>setNotice('Holdings refreshed.')).catch(e=>setNotice(e.message)):setWalletOpen(true)}/>
          <LobbyWidget round={displayRound}/>
        </aside>
        <section className="lower-grid"><LeaderPreview hasLeaders={leaders.length>0}><Leaderboard rows={leaders.slice(0,3)}/></LeaderPreview><LoopWidget/></section></div>
      </>}
      {page==='leaderboard'&&<section className="full-panel"><div className="section-title"><h2>ALL-TIME LEADERBOARD</h2><span>CONFIRMED NFT AWARDS ONLY</span></div>{leaders.length?<Leaderboard rows={leaders}/>:<Empty icon={<Trophy size={44}/>} title="The leaderboard starts with you." text="Confirmed PvP winners will appear here. Practice results never count."/>}</section>}
      {page==='profile'&&<section className="full-panel">{!player?<Empty icon={<Wallet size={44}/>} title="Make it your arena." text="Connect your wallet to see your match history and won cards." action={<Button onClick={()=>setWalletOpen(true)}>Connect wallet</Button>}/>:<><div className="profile-heading"><span className="profile-avatar"><Crosshair size={38}/></span><div><h2>{player.name}</h2><a href={`https://solscan.io/account/${player.wallet}`} target="_blank" rel="noreferrer">{shortWallet(player.wallet)} <ExternalLink size={12}/></a></div><div className="profile-stats"><b>{profile?.wins??0}<small>WINS</small></b><b>{money(profile?.valueWon)}<small>EST. VALUE WON</small></b><b>{profile?.bestScore??0}<small>BEST SCORE</small></b></div></div><form className="name-form" onSubmit={async e=>{e.preventDefault();try{await api('/me',{name},'PATCH');await game.refreshPlayer();setNotice('Profile updated.');}catch(error){setNotice((error as Error).message);}}}><Label htmlFor="display-name">Display name</Label><Input id="display-name" value={name} maxLength={24} onChange={e=>setName(e.target.value)} required/><Button type="submit" variant="outline">Save name</Button></form><div className="profile-access"><ShieldCheck size={17}/><span>{holding?.configured?holding.eligible?'Eligible to play':'More tokens needed':'Eligibility available at token launch'}</span>{holding?.configured&&<b>{holding.percent}% held</b>}</div><h3 className="subheading">YOUR TROPHY CASE</h3>{profile?.prizes?.length?<div className="prize-collection">{profile.prizes.map((p:any)=><a key={p.id} href={`https://solscan.io/tx/${p.transferSignature}`} target="_blank" rel="noreferrer"><img src={p.image} alt={p.name} width={240} height={336} loading="lazy" decoding="async" referrerPolicy="no-referrer"/><strong>{p.name}</strong><span>{money(p.value)} estimated · View transfer ↗</span></a>)}</div>:<Empty icon={<Trophy size={30}/>} title="Your first grail is out there." text="Cards you win remain in your history, even after you transfer them."/>}<h3 className="subheading">MATCH HISTORY</h3>{profile?.matches?.length?<Table><TableHeader><TableRow><TableHead>Round</TableHead><TableHead>Score</TableHead><TableHead>Shots</TableHead><TableHead>Result</TableHead></TableRow></TableHeader><TableBody>{profile.matches.map((m:any)=><TableRow key={m.id}><TableCell>#{m.number}</TableCell><TableCell>{m.score}</TableCell><TableCell>{m.shots}</TableCell><TableCell>{m.winner===player.wallet?'Won':m.status}</TableCell></TableRow>)}</TableBody></Table>:<p className="dim">Your live matches will appear here.</p>}</>}</section>}
      {page==='admin'&&<section className="full-panel">{!player?.owner?<Empty icon={<ShieldCheck size={44}/>} title="Owner access required." text="Sign in with the configured owner wallet to manage the treasury." action={<Button onClick={()=>setWalletOpen(true)}>Connect owner wallet</Button>}/>:<><h2>Launch readiness</h2><ul className="blockers">{treasury?.blockers.map(b=><li key={b}>{b}</li>)}</ul>{treasury?.error&&<p className="notice">{treasury.error}</p>}{settings&&<form className="settings-form" onSubmit={async e=>{e.preventDefault();try{await api('/admin/settings',settings,'PATCH');setNotice('Controls saved.');}catch(error){setNotice((error as Error).message);}}}><Label htmlFor="paused">Pause new rounds and spending<Switch id="paused" checked={settings.paused} onCheckedChange={paused=>setSettings({...settings,paused})}/></Label><Label>Unlimited daily spending<Switch checked={settings.dailyCapUsd===null} onCheckedChange={unlimited=>setSettings({...settings,dailyCapUsd:unlimited?null:100})}/><small>Uses confirmed funds after reserves.</small></Label>{settings.dailyCapUsd!==null&&<Label>Daily spending cap (USD)<Input type="number" min="0" value={settings.dailyCapUsd} onChange={e=>setSettings({...settings,dailyCapUsd:Number(e.target.value)})}/></Label>}{([['gasReserveSol','Gas reserve (SOL)'],['slippageBps','Maximum slippage (basis points)']] as const).map(([key,label])=><Label key={key}>{label}<Input type="number" step={key==='gasReserveSol'?'.01':'1'} min="0" value={settings[key]} onChange={e=>setSettings({...settings,[key]:Number(e.target.value)})}/></Label>)}<p className="funded-rounds-note">Rounds open whenever a pack is funded. Players get 30 seconds to join; at least two eligible holders must be online.</p><Button type="submit">Save controls</Button></form>}<h3 className="subheading">RECOVERY QUEUE</h3><p className="dim">Temporary errors retry automatically. Validation failures and held results require owner review.</p>{purchaseError&&<p className="notice" role="alert"><strong>Pack purchase stopped: </strong>{purchaseError}</p>}{jobs.length?jobs.map(job=><div className="recovery-job" key={job.id}><div><b>{job.kind} · {job.status}</b><p>{job.error||job.id}</p></div><Button variant="outline" onClick={async()=>{try{await api('/admin/recover',{id:job.id});setNotice('Recovery requested. Existing transactions will be reconciled first.');}catch(e){setNotice((e as Error).message);}}}>Recover</Button></div>):<p className="dim">No stalled transactions.</p>}<Button variant="outline" onClick={async()=>{try{await api('/admin/round/recover',{});setNotice('Round recovery requested.');}catch(e){setNotice((e as Error).message);}}}>Retry paused round</Button><OwnerReview onNotice={setNotice}/></>}</section>}
    </main>
    <footer className="site-footer"><a className="footer-brand" href="/"><Crosshair size={18}/>GRAILSHOT<span>HOLD. AIM. WIN.</span></a><div><span>HOLDER VS HOLDER · BUILT ON SOLANA</span><a href="https://collectorcrypt.com" target="_blank" rel="noreferrer">Cards via Collector Crypt<ArrowUpRight size={13}/></a></div></footer>
    <Dialog open={walletOpen} onOpenChange={setWalletOpen}><DialogContent><DialogHeader><DialogTitle>Take your place in the arena.</DialogTitle><DialogDescription>Connect a Solana wallet and sign a message to verify it’s yours. Playing never asks you to approve a transaction.</DialogDescription></DialogHeader><div className="wallet-list">{wallets.length?wallets.map(w=><Button key={w.name} variant="outline" disabled={busy} onClick={()=>connect(w)}><img src={w.icon} alt="" width={26} height={26}/>{w.name}<ArrowRight size={15}/></Button>):<p>No Solana wallet detected. Open this page in a browser with <a href="https://phantom.com" target="_blank" rel="noreferrer">Phantom</a> or <a href="https://solflare.com" target="_blank" rel="noreferrer">Solflare</a> installed.</p>}</div>{notice&&<p className="orange">{notice}</p>}</DialogContent></Dialog>
    <Dialog open={rules} onOpenChange={setRules}><DialogContent><DialogHeader><DialogTitle>Hold. Aim. Win.</DialogTitle><DialogDescription>Live PvP against other holders — one real card per round.</DialogDescription></DialogHeader><ol className="rules-list"><li><b>Hold 0.1%.</b> Connect and sign in. Your balance is checked before entry, at registration close, and before a winner is confirmed.</li><li><b>Join the live round.</b> At least two eligible holders must be online before a pack is purchased. Registration lasts 30 seconds.</li><li><b>Make ten shots count.</b> Each target flashes for 600 ms after an unpredictable pause. One shot per target: 70 points for reaction speed and 30 for accuracy. Misses score zero. The highest score wins.</li><li><b>Break the tie.</b> Tied leaders get five more targets, up to three times. An unresolved tie carries the prize forward.</li><li><b>Receive your grail.</b> The card NFT transfers to the winner’s wallet. Interrupted matches keep the prize for a new round.</li></ol><p className="dim">The server verifies scores and rejects repeated shots. Suspicious results may be held for review. Network compensation is capped at 75 ms.</p></DialogContent></Dialog>
  </div>;
}
function Leaderboard({rows}:{rows:any[]}){return <Table><TableHeader><TableRow><TableHead>RANK</TableHead><TableHead>PLAYER</TableHead><TableHead>WINS</TableHead><TableHead>VALUE WON</TableHead><TableHead>BEST</TableHead></TableRow></TableHeader><TableBody>{rows.map((p,i)=><TableRow key={p.wallet}><TableCell className={i===0?'orange':''}>#{String(i+1).padStart(2,'0')}</TableCell><TableCell><strong>{p.name}</strong><small className="wallet-caption">{shortWallet(p.wallet)}</small></TableCell><TableCell>{p.wins}</TableCell><TableCell>{money(p.valueWon)}</TableCell><TableCell>{p.bestScore}</TableCell></TableRow>)}</TableBody></Table>;}
function Empty({icon,title,text,action}:{icon:React.ReactNode;title:string;text:string;action?:React.ReactNode}){return <div className="empty-state">{icon}<h3>{title}</h3><p>{text}</p>{action}</div>;}


