import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import websocket from '@fastify/websocket';
import rateLimit from '@fastify/rate-limit';
import type { WebSocket } from 'ws';
import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import { config } from './config';
import { trustInternalProxies } from './proxy';
import { challenge, verify, sessionPlayer, hashSession } from './auth';
import { openDatabase, migrate, Serial, audit, type Database } from './db';
import { Jobs, PendingOperation } from './jobs';
import { Chain } from './chain';
import { Providers } from './providers';
import { Treasury } from './treasury';
import { Engine } from './engine';
import type { Player } from '../shared/types';
import { CONNECTION_LIMITS, originAllowed, latencyCredit } from './security';
type Client={socket:WebSocket;player:Player|null;token?:string;ip:string;pending:Map<string,number>;rtts:number[];latencyFloor:number;lastAck:number;messages:number;window:number;targetKey:string;processing:boolean};
export async function createApp(options:{db?:Database;chain?:Chain;providers?:Providers;timers?:boolean;logger?:boolean}={}){
  const app=Fastify({logger:options.logger??true,bodyLimit:16_384,requestTimeout:15_000,trustProxy:trustInternalProxies(config.TRUST_PROXY_HOPS)});await app.register(cookie);await app.register(rateLimit,{max:120,timeWindow:'1 minute'});await app.register(websocket,{options:{maxPayload:4096,perMessageDeflate:false}});
  const db=options.db??await openDatabase();await migrate(db);const serial=new Serial(),jobs=new Jobs(db),chain=options.chain??new Chain(jobs);await chain.init();const providers=options.providers??new Providers(chain,jobs),treasury=new Treasury(db,chain,providers);await treasury.init();
  const clients=new Set<Client>();const online=(wallet:string)=>[...clients].some(c=>c.player?.wallet===wallet&&c.socket.readyState===1&&Date.now()-c.lastAck<12_000);
  const engine=new Engine(db,treasury,online);await engine.init();
  let broadcastTimer:ReturnType<typeof setTimeout>|undefined,closing=false;
  const flush=()=>{broadcastTimer=undefined;if(closing)return;const serverTime=Date.now(),onlineCount=new Set([...clients].filter(x=>x.player&&x.socket.readyState===1&&serverTime-x.lastAck<12_000).map(x=>x.player!.wallet)).size;for(const c of clients){if(c.socket.readyState!==1)continue;if(c.socket.bufferedAmount>200_000){c.socket.close(1013,'Connection is too slow');continue;}c.socket.send(JSON.stringify({type:'snapshot',data:{serverTime,round:engine.view(c.player?.wallet,serverTime),treasury:{...treasury.view,blockers:c.player?.owner?treasury.view.blockers:[],error:c.player?.owner?treasury.view.error:null},online:onlineCount,mode:config.live?'mainnet':'local',mint:config.MEMECOIN_MINT||null}}));}};
  const broadcast=()=>{if(!closing&&!broadcastTimer)broadcastTimer=setTimeout(flush,50);};
  app.addHook('onRequest',async(req,reply)=>{if(!originAllowed(req.method,req.headers.origin,req.headers['sec-fetch-site'] as string|undefined,config.APP_ORIGIN))return reply.code(403).send({error:'Request origin is not allowed.'});});
  app.addHook('onSend',async(_req,reply,payload)=>{reply.header('Cache-Control','no-store').header('X-Content-Type-Options','nosniff').header('X-Frame-Options','DENY').header('Referrer-Policy','no-referrer');return payload;});
  const auth=async(req:any,owner=false)=>{const player=await sessionPlayer(db,req.cookies.gs_session);if(!player)throw Object.assign(new Error('Connect and sign in with your wallet.'),{statusCode:401});if(owner&&!player.owner)throw Object.assign(new Error('Owner access required.'),{statusCode:403});return player;};
  app.setErrorHandler((error,req,reply)=>{const e=error as Error&{statusCode?:number};if(e instanceof z.ZodError)return reply.code(400).send({error:'Check the submitted fields.',fields:e.issues.map(i=>i.path.join('.'))});app.log.error({message:e.message,path:req.url},'Request failed');return reply.code(e.statusCode??400).send({error:e.message});});
  app.get('/api/health',{config:{rateLimit:false}},async(_req,reply)=>{
    try{await db.query('SELECT 1');}catch{return reply.code(503).send({ok:false,service:'grailshot'});}
    return{ok:true,service:'grailshot',database:config.DATABASE_URL?'postgres':'embedded-postgres',spendingEnabled:config.live&&treasury.view.ready&&!treasury.settings.paused};
  });
  app.get('/api/me',async req=>({player:await sessionPlayer(db,req.cookies.gs_session)}));
  app.post('/api/auth/challenge',{config:{rateLimit:{max:12,timeWindow:'1 minute'}}},async req=>{const{wallet}=z.object({wallet:z.string().min(32).max(44)}).parse(req.body);return serial.run(()=>challenge(db,wallet));});
  app.post('/api/auth/verify',{config:{rateLimit:{max:12,timeWindow:'1 minute'}}},async(req,reply)=>{const body=z.object({id:z.string().uuid(),signature:z.string().max(100)}).parse(req.body);const result=await serial.run(()=>verify(db,body.id,body.signature));reply.setCookie('gs_session',result.token,{path:'/',httpOnly:true,sameSite:'strict',secure:config.APP_ORIGIN.startsWith('https:'),maxAge:86_400});return{wallet:result.wallet};});
  app.post('/api/auth/logout',async(req,reply)=>{if(req.cookies.gs_session)await serial.run(()=>db.query('DELETE FROM sessions WHERE id=$1',[hashSession(req.cookies.gs_session!)]));for(const c of clients)if(c.token===req.cookies.gs_session)c.socket.close(1000,'Signed out');reply.clearCookie('gs_session',{path:'/'});return{ok:true};});
  app.get('/api/eligibility',{config:{rateLimit:{max:12,timeWindow:'1 minute'}}},async req=>{const player=await auth(req);try{return await chain.eligibility(player.wallet);}catch{throw new Error('Holdings verification is temporarily unavailable. Please try again.');}});
  app.patch('/api/me',async req=>{const player=await auth(req),{name}=z.object({name:z.string().trim().min(2).max(24).regex(/^[\p{L}\p{N} _.-]+$/u)}).parse(req.body);await serial.run(async()=>{await db.query('UPDATE players SET name=$2 WHERE wallet=$1',[player.wallet,name]);await engine.reloadStandings();});for(const c of clients)if(c.player?.wallet===player.wallet)c.player.name=name;broadcast();return{ok:true};});
  app.get('/api/treasury',async req=>{const p=await sessionPlayer(db,req.cookies.gs_session);return{...treasury.view,blockers:p?.owner?treasury.view.blockers:[],error:p?.owner?treasury.view.error:null};});
  app.get('/api/rounds/current',async req=>engine.view((await sessionPlayer(db,req.cookies.gs_session))?.wallet));
  app.post('/api/rounds/join',{config:{rateLimit:{max:10,timeWindow:'1 minute'}}},async req=>{const player=await auth(req);await serial.run(()=>engine.join(player.wallet));broadcast();return{ok:true};});
  app.get('/api/leaderboard',async()=>{const rows=(await db.query("SELECT p.wallet,p.name,COUNT(a.id)::int AS wins,COALESCE(SUM((a.data->>'value')::numeric),0)::float8 AS \"valueWon\",COALESCE((SELECT MAX(e.score) FROM entries e JOIN rounds r ON r.id=e.round_id WHERE e.wallet=p.wallet AND r.status='complete' AND NOT e.disqualified),0)::int AS \"bestScore\" FROM players p JOIN prizes a ON a.winner=p.wallet AND a.status='awarded' GROUP BY p.wallet,p.name ORDER BY wins DESC,\"valueWon\" DESC,\"bestScore\" DESC,p.wallet LIMIT 100")).rows;return{players:rows};});
  app.get('/api/profiles/:wallet',async req=>{const{wallet}=z.object({wallet:z.string().min(32).max(44)}).parse(req.params);const player=(await db.query('SELECT wallet,name FROM players WHERE wallet=$1',[wallet])).rows[0];if(!player)throw Object.assign(new Error('Profile not found.'),{statusCode:404});const prizes=(await db.query("SELECT data FROM prizes WHERE winner=$1 AND status='awarded'",[wallet])).rows.map(p=>p.data);const matches=(await db.query("SELECT r.id,r.number,r.status,r.data->>'winner' AS winner,e.score,e.shots,e.disqualified FROM entries e JOIN rounds r ON r.id=e.round_id WHERE e.wallet=$1 ORDER BY r.number DESC LIMIT 100",[wallet])).rows;return{...player,prizes,matches,wins:prizes.length,valueWon:prizes.reduce((s,p)=>s+Number(p.value??0),0),bestScore:Math.max(0,...matches.filter(m=>m.status==='complete'&&!m.disqualified).map(m=>Number(m.score)))};});
  app.get('/api/admin',async req=>{await auth(req,true);return{settings:treasury.settings,treasury:treasury.view,round:engine.current,jobs:(await db.query("SELECT id,kind,status,error,created_at,updated_at FROM jobs WHERE status NOT IN('confirmed','complete') ORDER BY created_at DESC LIMIT 100")).rows,audit:(await db.query('SELECT * FROM audit ORDER BY id DESC LIMIT 50')).rows};});
  app.patch('/api/admin/settings',async req=>{const player=await auth(req,true);const settings=z.object({paused:z.boolean(),dailyCapUsd:z.number().finite().min(0).max(1_000_000),gasReserveSol:z.number().finite().min(.01).max(100),slippageBps:z.number().int().min(1).max(100),cadence:z.object({fastRate:z.number().nonnegative(),fastBalance:z.number().nonnegative(),mediumRate:z.number().nonnegative(),mediumBalance:z.number().nonnegative()})}).parse(req.body);if(settings.cadence.fastRate<settings.cadence.mediumRate||settings.cadence.fastBalance<settings.cadence.mediumBalance)throw new Error('Fast thresholds must be at least the medium thresholds.');await serial.run(async()=>{await treasury.save(settings);await audit(db,'settings-updated',{wallet:player.wallet,settings});});broadcast();return{ok:true};});
  app.post('/api/admin/recover',async req=>{const player=await auth(req,true);const{id}=z.object({id:z.string().max(160)}).parse(req.body);await serial.run(async()=>{await chain.recover(id);if(id.endsWith(':payment')){const parentId=id.slice(0,-8),parent=await jobs.get(parentId),payment=await jobs.get(id);if(parent&&payment?.status==='retryable'){const status=await providers.cc(`/pack/status?memo=${encodeURIComponent(parent.data.memo)}`);if(status.pack?.status==='confirmed')throw new Error('Provider has a confirmed payment. Do not rebuild this pack.');delete parent.data.memo;delete parent.data.transaction;await jobs.put(parentId,'pack','purchasing',parent.data);}}await audit(db,'job-recovery',{wallet:player.wallet,id});if(engine.current?.status==='review'&&!engine.current.reviewReason)await engine.recover();});return{ok:true};});
  app.get('/api/admin/round/shots',async req=>{await auth(req,true);return{round:engine.current,shots:engine.current?(await db.query('SELECT * FROM shots WHERE round_id=$1 ORDER BY received_at',[engine.current.id])).rows:[]};});
  app.post('/api/admin/round/recover',async req=>{const player=await auth(req,true);const{approveWinner,requeue}=z.object({approveWinner:z.boolean().default(false),requeue:z.boolean().default(false)}).parse(req.body);await serial.run(async()=>{if(requeue){if(!engine.current?.prize||engine.current.status!=='review')throw new Error('Only a reviewed prize can be requeued.');const transfer=await jobs.get(`award:${engine.current.prize.id}`);if(transfer)throw new Error('A transfer is already recorded; reconcile it first.');await engine.carry('The reviewed round was voided. Its prize returns to the arena.');}else await engine.recover(approveWinner);await audit(db,'round-recovery',{wallet:player.wallet,round:engine.current?.id,approveWinner,requeue});});broadcast();return{ok:true};});
  app.get('/api/ws',{websocket:true},(socket,req)=>{
    if(req.headers.origin!==config.APP_ORIGIN){app.log.warn({origin:req.headers.origin,expected:config.APP_ORIGIN},'Rejected game connection origin');socket.close(1008,'Invalid origin');return;}
    if(clients.size>=CONNECTION_LIMITS.total||[...clients].filter(c=>c.ip===req.ip).length>=CONNECTION_LIMITS.perIp){socket.close(1013,'Too many connections');return;}
    const c:Client={socket,player:null,token:req.cookies.gs_session,ip:req.ip,pending:new Map(),rtts:[],latencyFloor:Infinity,lastAck:Date.now(),messages:0,window:Date.now(),targetKey:'',processing:false};clients.add(c);
    const playerPromise=sessionPlayer(db,c.token).then(p=>{if(p&&[...clients].filter(other=>other!==c&&other.player?.wallet===p.wallet).length>=CONNECTION_LIMITS.perWallet){socket.close(1008,'Too many tabs for this wallet');return null;}if(socket.readyState!==1)return null;c.player=p;broadcast();return p;}).catch(()=>{socket.close(1011,'Sign-in is temporarily unavailable');return null;});
    socket.on('message',async raw=>{const receivedAt=Date.now();try{if(receivedAt-c.window>1000){c.window=receivedAt;c.messages=0;}if(++c.messages>30){socket.close(1008,'Message rate exceeded');return;}const data=z.object({type:z.enum(['ping','ack','shot']),id:z.string().max(80).optional(),roundId:z.string().uuid().optional(),targetId:z.string().uuid().optional(),x:z.number().finite().optional(),y:z.number().finite().optional()}).parse(JSON.parse(raw.toString()));
      if(data.type==='ping'){socket.send(JSON.stringify({type:'pong',id:data.id}));return;}
      if(data.type==='ack'){const sent=c.pending.get(data.id!);if(sent!==undefined){c.pending.delete(data.id!);c.rtts=[...c.rtts.slice(-9),receivedAt-sent];c.latencyFloor=Math.min(c.latencyFloor,receivedAt-sent);c.lastAck=receivedAt;}return;}
      if(c.processing){socket.send(JSON.stringify({type:'error',message:'A shot is already being checked.'}));return;}c.processing=true;
      try{
      const player=await playerPromise;if(!player||!await sessionPlayer(db,c.token))throw new Error('Your wallet session expired. Sign in again.');
      if(data.x===undefined||data.y===undefined||!data.targetId||!data.roundId)throw new Error('Incomplete shot.');const latency=latencyCredit(c.rtts,c.latencyFloor);
      await serial.run(()=>engine.shot(player.wallet,data.roundId!,data.targetId!,data.x!,data.y!,receivedAt,latency));broadcast();
      }finally{c.processing=false;}
    }catch(error){if(socket.readyState===1)socket.send(JSON.stringify({type:'error',message:(error as Error).message}));}});
    socket.on('close',()=>{clients.delete(c);broadcast();});socket.on('error',()=>clients.delete(c));
  });
  let busy=false;const intervals:ReturnType<typeof setInterval>[]=[];
  // Publish each appearance promptly; the regular lobby snapshot is too slow for a 600 ms flash.
  if(options.timers!==false)intervals.push(setInterval(()=>{const serverTime=Date.now();for(const c of clients){if(c.socket.readyState!==1||c.socket.bufferedAmount>200_000)continue;const round=engine.view(c.player?.wallet,serverTime),target=round?.target??null,key=`${round?.id??''}:${target?.id??''}`;if(key===c.targetKey)continue;c.targetKey=key;c.socket.send(JSON.stringify({type:'target',roundId:round?.id,target,serverTime}));}},20));
  if(options.timers!==false){intervals.push(setInterval(()=>{if(busy)return;busy=true;const before=`${engine.current?.id}:${engine.current?.status}`;serial.run(()=>engine.step()).catch(error=>app.log.error({message:error.message},'Coordinator error')).finally(()=>{busy=false;if(before!==`${engine.current?.id}:${engine.current?.status}`)broadcast();});},100));intervals.push(setInterval(broadcast,500));intervals.push(setInterval(()=>{for(const c of clients){if(Date.now()-c.lastAck>15_000){c.socket.terminate();continue;}const id=randomUUID();c.pending.set(id,Date.now());for(const[k,v]of c.pending)if(Date.now()-v>15_000)c.pending.delete(k);if(c.socket.readyState===1)c.socket.send(JSON.stringify({type:'heartbeat',id}));}},2000));intervals.push(setInterval(()=>{for(const c of clients)if(c.player)sessionPlayer(db,c.token).then(p=>{if(!p){c.player=null;c.socket.close(1008,'Session expired');}}).catch(()=>{c.player=null;c.socket.close(1011,'Session unavailable');});},30_000));intervals.push(setInterval(()=>{serial.run(async()=>{await db.query('DELETE FROM sessions WHERE expires_at<$1',[Date.now()]);await db.query('DELETE FROM challenges WHERE expires_at<$1',[Date.now()]);}).catch(()=>{});},300_000));}
  app.addHook('onClose',async()=>{closing=true;clearTimeout(broadcastTimer);for(const interval of intervals)clearInterval(interval);for(const c of clients)c.socket.terminate();await serial.run(()=>db.close());});
  return{app,db,engine,treasury,chain,jobs,clients,serial,broadcast};
}
